//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 1003.2.11.101.0
//

#ifndef NCNotificationViewController_h
#define NCNotificationViewController_h
@import Foundation;

#include "NCAuxiliaryOptionsProviding-Protocol.h"
#include "NCDimmableView.h"
#include "NCMaterialDisplaying-Protocol.h"
#include "NCNotificationCustomContent-Protocol.h"
#include "NCNotificationCustomContentDelegate-Protocol.h"
#include "NCNotificationCustomContentProviding-Protocol.h"
#include "NCNotificationListCellDynamicHeightTraits.h"
#include "NCNotificationListDimmable-Protocol.h"
#include "NCNotificationListZPositionable-Protocol.h"
#include "NCNotificationLookView-Protocol.h"
#include "NCNotificationRequestInlineActionsProviderDelegate-Protocol.h"
#include "NCNotificationRequestPresenting-Protocol.h"
#include "NCNotificationStaticContentProviding-Protocol.h"
#include "NCNotificationViewControllerDelegate-Protocol.h"
#include "PLContentSizeCategoryAdjusting-Protocol.h"
#include "PLContentSizeManaging-Protocol.h"
#include "PLExpandedPlatterPresentationControllerDelegate-Protocol.h"

@class NCNotificationRequest, UIColor, UIPanGestureRecognizer, UIView, UIViewController;
@protocol UIViewControllerTransitionCoordinator;

@interface NCNotificationViewController : UIViewController <NCMaterialDisplaying, NCNotificationCustomContentDelegate, NCNotificationListDimmable, NCNotificationListZPositionable, NCNotificationRequestInlineActionsProviderDelegate, NCNotificationRequestPresenting, PLContentSizeCategoryAdjusting, PLExpandedPlatterPresentationControllerDelegate> {
    /* instance variables */
    id <UIViewControllerTransitionCoordinator> _activeTransitionCoordinator;
    _Bool _allowContentToCrossFade;
    long long _apparentZDistanceToUser;
    UIView *_associatedView;
    id <NCAuxiliaryOptionsProviding> _auxiliaryOptionsContentProvider;
    double _backgroundAlpha;
    _Bool _backgroundHidden;
    _Bool _canPan;
    double _compositeAlpha;
    double _contentAlpha;
    _Bool _contentReplacedWithSnapshot;
    UIView<PLContentSizeManaging> *_contentSizeManagingView;
    struct CGAffineTransform { double a; double b; double c; double d; double tx; double ty; } _contentTransform;
    UIPanGestureRecognizer *_customContentHomeAffordanceGestureRecognizer;
    _Bool _customContentHomeAffordanceVisible;
    id <NCNotificationCustomContentProviding> _customContentProvider;
    UIViewController<NCNotificationCustomContent> *_customContentProvidingViewController;
    double _dateAlpha;
    id <NCNotificationViewControllerDelegate> _delegate;
    _Bool _didQueryCanPan;
    _Bool _disableDimming;
    unsigned long long _glassMode;
    _Bool _hasShadow;
    _Bool _hideDate;
    _Bool _interactionEnabled;
    UIView<NCNotificationLookView> *_lookView;
    NSString *_materialGroupNameBase;
    long long _ncTransitionAnimationState;
    _Bool _notificationContentViewHidden;
    NCNotificationRequest *_notificationRequest;
    NSHashTable *_observers;
    id /* block */ _pendingPresentationTransitionDidEndBlock;
    NSMapTable *_reasonsToTransitionBlockingAssertions;
    _Bool _revealAdditionalContentOnPresentation;
    double _rootScrollVelocity;
    _Bool _shouldRestorePresentingShortLookOnDismiss;
    id <NCNotificationStaticContentProviding> _staticContentProvider;
    _Bool _unmanagedBackdropContrast;
}

@property (readonly, copy, nonatomic) NSSet *activeTransitionBlockingAssertions;
@property (retain, nonatomic) id <UIViewControllerTransitionCoordinator> activeTransitionCoordinator;
@property (nonatomic) _Bool adjustsFontForContentSizeCategory;
@property (nonatomic) _Bool allowContentToCrossFade;
@property (nonatomic) long long apparentZDistanceToUser;
@property (weak, nonatomic) UIView *associatedView;
@property (retain, nonatomic) id <NCAuxiliaryOptionsProviding> auxiliaryOptionsContentProvider;
@property (nonatomic) double backgroundAlpha;
@property (nonatomic) _Bool backgroundHidden;
@property (readonly, nonatomic) _Bool committedToPresentingCustomContentProvidingViewController;
@property (nonatomic) double compositeAlpha;
@property (nonatomic) double contentAlpha;
@property (nonatomic) _Bool contentReplacedWithSnapshot;
@property (nonatomic) struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; } contentTransform;
@property (readonly, nonatomic) NCNotificationListCellDynamicHeightTraits *currentTraits;
@property (weak, nonatomic) UIPanGestureRecognizer *customContentHomeAffordanceGestureRecognizer;
@property (nonatomic) _Bool customContentHomeAffordanceVisible;
@property (retain, nonatomic) id <NCNotificationCustomContentProviding> customContentProvider;
@property (retain, nonatomic) UIViewController<NCNotificationCustomContent> *customContentProvidingViewController;
@property (nonatomic) double dateAlpha;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id <NCNotificationViewControllerDelegate> delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) _Bool disableDimming;
@property (nonatomic) unsigned long long glassMode;
@property (nonatomic) _Bool hasShadow;
@property (readonly) unsigned long long hash;
@property (nonatomic) _Bool hideDate;
@property (readonly, nonatomic) _Bool highlighted;
@property (nonatomic) _Bool interactionEnabled;
@property (readonly, nonatomic) _Bool lookStyleLongLook;
@property (copy, nonatomic) NSString *materialGroupNameBase;
@property (nonatomic) long long materialRecipe;
@property (copy, nonatomic) UIColor *materialTintColor;
@property (readonly, nonatomic) _Bool notPresentingOrHasCommittedToDismissingCustomContentProvidingViewController;
@property (nonatomic) _Bool notificationContentViewHidden;
@property (copy, nonatomic) NCNotificationRequest *notificationRequest;
@property (readonly, copy, nonatomic) NSDictionary *notificationUsageTrackingState;
@property (readonly, nonatomic) NCDimmableView *notificationViewControllerView;
@property (copy, nonatomic) id /* block */ pendingPresentationTransitionDidEndBlock;
@property (copy, nonatomic) NSString *preferredContentSizeCategory;
@property (readonly, nonatomic) NCNotificationViewController *presentedLongLookViewController;
@property (readonly, nonatomic) _Bool presentingCustomContentProvidingViewController;
@property (nonatomic) _Bool revealAdditionalContentOnPresentation;
@property (nonatomic) double rootScrollVelocity;
@property (readonly, nonatomic) _Bool shortLook;
@property (nonatomic) _Bool shouldRestorePresentingShortLookOnDismiss;
@property (retain, nonatomic) id <NCNotificationStaticContentProviding> staticContentProvider;
@property (readonly) Class superclass;
@property (nonatomic) _Bool supportsMitosis;
@property (nonatomic) _Bool unmanagedBackdropContrast;

/* class methods */
+ (id)_primaryTextFont;
+ (double)prominentIconDimension;

/* instance methods */
- (id)_activeTransitionCoordinator;
- (void)_askDelegateToExecuteAction:(id)action withParameters:(id)parameters animated:(_Bool)animated;
- (_Bool)_canPan;
- (id)_contentSizeManagingView;
- (id)_customContentProvidingViewController;
- (id)_customContentProvidingViewControllerCreateIfNecessary;
- (long long)_dateFormatStyle;
- (void)_dismissPresentedViewControllerAnimated:(_Bool)animated;
- (void)_executeCancelAction:(_Bool)action;
- (void)_executeClearAction:(_Bool)action;
- (void)_executeCloseAction:(_Bool)action;
- (void)_executeDefaultAction:(_Bool)action;
- (void)_executeNilAction:(_Bool)action;
- (id)_initWithNotificationRequest:(id)request revealingAdditionalContentOnPresentation:(_Bool)presentation;
- (_Bool)_isPresentingCustomContentProvidingViewController;
- (void)_loadLookView;
- (id)_lookView;
- (id)_lookViewIfLoaded;
- (id)_lookViewLoadingIfNecessary:(_Bool)necessary;
- (unsigned long long)_maximumNumberOfPrimaryTextLinesForProvidedStaticContent;
- (unsigned long long)_maximumNumberOfSecondaryTextLinesForProvidedStaticContent;
- (id)_notificationViewControllerView;
- (void)_notificationViewControllerViewDidLoad;
- (void)_notifyObserversWithBlock:(id /* block */)block;
- (id /* block */)_pendingPresentationTransitionDidEndBlock;
- (struct CGSize { double x0; double x1; })_preferredCustomContentSizeForSize:(struct CGSize { double x0; double x1; })size parentContentContainerBounds:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })bounds;
- (id)_presentedLongLookViewController;
- (void)_setActiveTransitionCoordinator:(id)coordinator;
- (void)_setCustomContentProvidingViewController:(id)controller;
- (_Bool)_setDelegate:(id)delegate;
- (_Bool)_setNotificationRequest:(id)request;
- (void)_setPendingPresentationTransitionDidEndBlock:(id /* block */)block;
- (void)_setPreferredCustomContentSize:(struct CGSize { double x0; double x1; })size;
- (void)_setShouldRestorePresentingShortLookOnDismiss:(_Bool)dismiss;
- (void)_setupAuxiliaryOptionsContentProvider;
- (void)_setupCustomContentProvider;
- (void)_setupStaticContentProvider;
- (_Bool)_shouldRestorePresentingShortLookOnDismiss;
- (id)_staticContentProviderLoadingIfNecessary;
- (void)_updateLookView:(id)view withTitleFromProvidedStaticContent:(id)content;
- (void)_updatePreferredContentSize;
- (void)_updateScreenCaptureProhibited;
- (void)_updateWithProvidedAuxiliaryOptionsContent;
- (void)_updateWithProvidedCustomContent;
- (void)_updateWithProvidedStaticContent;
- (id)activeTransitionBlockingAssertionForReason:(id)reason;
- (id)activeTransitionBlockingAssertions;
- (void)addObserver:(id)observer;
- (_Bool)adjustForContentSizeCategoryChange;
- (_Bool)adjustsFontForContentSizeCategory;
- (_Bool)allowContentToCrossFade;
- (long long)apparentZDistanceToUser;
- (id)associatedView;
- (id)auxiliaryOptionsContentProvider;
- (double)backgroundAlpha;
- (long long)backgroundGlassId;
- (unsigned long long)backgroundGlassState;
- (double)compositeAlpha;
- (void)configureStackDimmingForTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform;
- (id)containerViewForExpandedContent;
- (double)contentAlpha;
- (void)contentProvider:(id)provider performAction:(id)action animated:(_Bool)animated;
- (struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })contentTransform;
- (id)currentTraits;
- (void)customContent:(id)content forwardAction:(id)action forNotification:(id)notification withUserInfo:(id)info;
- (void)customContent:(id)content requestPermissionToExecuteAction:(id)action forNotification:(id)notification withUserInfo:(id)info completionHandler:(id /* block */)handler;
- (id)customContentHomeAffordanceGestureRecognizer;
- (id)customContentProvider;
- (void)customContentRequestsDefaultAction:(id)action;
- (void)customContentRequestsDismiss:(id)dismiss;
- (double)dateAlpha;
- (id)debugDescription;
- (id)delegate;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)prefix;
- (id)descriptionWithMultilinePrefix:(id)prefix;
- (_Bool)didForwardNotificationRequestToCustomContent:(id)content;
- (_Bool)didReceiveNotificationRequest:(id)request;
- (_Bool)disableDimming;
- (_Bool)dismissPresentedViewControllerAnimated:(_Bool)animated;
- (void)dismissViewControllerWithTransition:(int)transition completion:(id /* block */)completion;
- (void)expandAndPlayMedia;
- (id)expandedPlatterPresentationController:(id)controller keyboardAssertionForGestureWindow:(id)window;
- (unsigned long long)glassMode;
- (double)glassSmoothness;
- (void)handleWake:(_Bool)wake;
- (_Bool)hasCommittedToPresentingCustomContentProvidingViewController;
- (_Bool)hasShadow;
- (_Bool)hideDate;
- (id)hideHomeAffordanceAnimationSettingsForExpandedPlatterPresentationController:(id)controller;
- (id)initWithNotificationRequest:(id)request;
- (id)initWithNotificationRequest:(id)request revealingAdditionalContentOnPresentation:(_Bool)presentation;
- (void)invalidateContentProviders;
- (_Bool)isBackgroundHidden;
- (_Bool)isContentExtensionVisible:(id)visible;
- (_Bool)isContentReplacedWithSnapshot;
- (_Bool)isCustomContentHomeAffordanceVisible;
- (_Bool)isHighlighted;
- (_Bool)isInteractionEnabled;
- (_Bool)isLookStyleLongLook;
- (_Bool)isNotPresentingOrHasCommittedToDismissingCustomContentProvidingViewController;
- (_Bool)isNotificationContentViewHidden;
- (_Bool)isShortLook;
- (void)loadView;
- (id)materialGroupNameBase;
- (long long)materialRecipe;
- (long long)ncTransitionAnimationState;
- (id)notificationRequest;
- (id)notificationUsageTrackingState;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)container;
- (struct CGSize { double x0; double x1; })preferredContentSizeWithPresentationSize:(struct CGSize { double x0; double x1; })size containerSize:(struct CGSize { double x0; double x1; })size;
- (_Bool)prefersStatusBarHidden;
- (void)presentLongLookAnimated:(_Bool)animated trigger:(long long)trigger completion:(id /* block */)completion;
- (void)presentViewController:(id)controller animated:(_Bool)animated completion:(id /* block */)completion;
- (id)presentedExpandedPlatterViewController;
- (void)preserveInputViews;
- (void)reloadContentProviders;
- (void)removeLightEffectsIfNeeded;
- (void)removeObserver:(id)observer;
- (id)requestTransitionBlockingAssertionWithReason:(id)reason;
- (_Bool)restoreInputViews;
- (_Bool)revealAdditionalContentOnPresentation;
- (double)rootScrollVelocity;
- (void)setAdjustsFontForContentSizeCategory:(_Bool)category;
- (void)setAllowContentToCrossFade:(_Bool)fade;
- (void)setApparentZDistanceToUser:(long long)user;
- (void)setAssociatedView:(id)view;
- (void)setAuxiliaryOptionsContentProvider:(id)provider;
- (void)setBackgroundAlpha:(double)alpha;
- (void)setBackgroundHidden:(_Bool)hidden;
- (void)setCompositeAlpha:(double)alpha;
- (void)setContentAlpha:(double)alpha;
- (void)setContentReplacedWithSnapshot:(_Bool)snapshot;
- (void)setContentTransform:(struct CGAffineTransform { double x0; double x1; double x2; double x3; double x4; double x5; })transform;
- (void)setCustomContentHomeAffordanceGestureRecognizer:(id)recognizer;
- (void)setCustomContentHomeAffordanceVisible:(_Bool)visible;
- (void)setCustomContentProvider:(id)provider;
- (void)setDateAlpha:(double)alpha;
- (void)setDelegate:(id)delegate;
- (void)setDisableDimming:(_Bool)dimming;
- (void)setGlassMode:(unsigned long long)mode;
- (void)setHasShadow:(_Bool)shadow;
- (void)setHasUpdatedContent;
- (void)setHideDate:(_Bool)date;
- (void)setInteractionEnabled:(_Bool)enabled;
- (void)setMaterialGroupNameBase:(id)base;
- (void)setMaterialRecipe:(long long)recipe;
- (void)setNCTransitionAnimationState:(long long)state;
- (void)setNotificationContentViewHidden:(_Bool)hidden;
- (void)setNotificationRequest:(id)request;
- (void)setRevealAdditionalContentOnPresentation:(_Bool)presentation;
- (void)setRootScrollVelocity:(double)velocity;
- (void)setStaticContentProvider:(id)provider;
- (void)setSupportsMitosis:(_Bool)mitosis;
- (void)setUnmanagedBackdropContrast:(_Bool)contrast;
- (id)settleHomeAffordanceAnimationBehaviorDescriptionForExpandedPlatterPresentationController:(id)controller;
- (_Bool)shouldAutorotate;
- (_Bool)shouldCommitToExpandedPlatterPresentationWithFeedback;
- (_Bool)shouldRestorePresentingShortLookOnDismiss;
- (id)staticContentProvider;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)supportsMitosis;
- (id)unhideHomeAffordanceAnimationSettingsForExpandedPlatterPresentationController:(id)controller;
- (_Bool)unmanagedBackdropContrast;
- (void)updateContent;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidDisappear:(_Bool)disappear;
- (void)viewDidLoad;
- (void)viewDidMoveToWindow:(id)window shouldAppearOrDisappear:(_Bool)disappear;
- (void)viewWillAppear:(_Bool)appear;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewWillLayoutSubviews;

@end

#endif /* NCNotificationViewController_h */