//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 1003.2.11.101.0
//

#ifndef NCNotificationShortLookViewController_h
#define NCNotificationShortLookViewController_h
@import Foundation;

#include "NCExpandedPlatterObserving-Protocol.h"
#include "NCExpandedPlatterViewController.h"
#include "NCExpandedPlatterViewControllerDelegate-Protocol.h"
#include "NCNotificationLongLookViewController.h"
#include "NCNotificationShortLookViewDelegate-Protocol.h"
#include "NCNotificationViewController.h"
#include "NCNotificationViewControllerObserving-Protocol.h"
#include "PLClickPresentationInteractionManagerDelegate-Protocol.h"
#include "PLClickPresentationInteractionPresenting-Protocol.h"
#include "PLExpandedPlatterInteractionHosting-Protocol.h"
#include "PLExpandedPlatterInteractionManagerDelegate-Protocol.h"
#include "PLExpandedPlatterPresentationControllerDelegate-Protocol.h"
#include "UIDragInteractionDelegate-Protocol.h"
#include "UIGestureRecognizerDelegate-Protocol.h"
#include "UIPointerInteractionDelegate-Protocol.h"

@class PLClickPresentationInteractionManager, PLExpandedPlatterInteractionManager, UIBezierPath, UIPointerInteraction, UITapGestureRecognizer, UIView;
@protocol PLExpandedPlatterInteractionAnimating;

@interface NCNotificationShortLookViewController : NCNotificationViewController <NCExpandedPlatterObserving, NCExpandedPlatterViewControllerDelegate, NCNotificationShortLookViewDelegate, NCNotificationViewControllerObserving, PLClickPresentationInteractionManagerDelegate, PLClickPresentationInteractionPresenting, PLExpandedPlatterInteractionHosting, PLExpandedPlatterInteractionManagerDelegate, PLExpandedPlatterPresentationControllerDelegate, UIDragInteractionDelegate, UIGestureRecognizerDelegate, UIPointerInteractionDelegate> {
    /* instance variables */
    id <PLExpandedPlatterInteractionAnimating> _activeExpandedPlatterInteractionAnimator;
    PLClickPresentationInteractionManager *_clickPresentationInteractionManager;
    UIView *_containerViewForExpandedContent;
    NSMutableArray *_containerViewProviders;
    _Bool _didScrollPresentLongLookViewController;
    NSString *_expandedPlatterDismissalReason;
    int _expandedPlatterPresentationState;
    NCExpandedPlatterViewController *_expandedPlatterViewController;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _finalPresentedFrameOfViewForPreview;
    PLExpandedPlatterInteractionManager *_interactionManager;
    NCNotificationLongLookViewController *_longLookNotificationViewController;
    UIView *_lookViewWrapper;
    UIPointerInteraction *_pointerInteraction;
    NSDate *_tapBeginTime;
    UITapGestureRecognizer *_tapGesture;
    long long _trigger;
}

@property (retain, nonatomic) id <PLExpandedPlatterInteractionAnimating> activeExpandedPlatterInteractionAnimator;
@property (readonly, nonatomic) PLClickPresentationInteractionManager *clickPresentationInteractionManager;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) _Bool didScrollPresentLongLookViewController;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } finalDismissedFrameOfViewForPreview;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } finalPresentedFrameOfViewForPreview;
@property (readonly) unsigned long long hash;
@property (nonatomic) _Bool highlighted;
@property (readonly, nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } initialPresentedFrameOfViewForPreview;
@property (readonly) Class superclass;
@property (readonly, nonatomic) UIView *viewForPreview;
@property (readonly, copy, nonatomic) UIBezierPath *visiblePath;

/* class methods */
+ (void)_playNegativeInteractionHaptic;
+ (void)_prepareSharedNotificationFeedbackGenerator;
+ (id)_sharedNotificationFeedbackGenerator;

/* instance methods */
- (id)_activeExpandedPlatterInteractionAnimator;
- (void)_askDelegateToExecuteAction:(id)action withParameters:(id)parameters animated:(_Bool)animated;
- (_Bool)_canShowWhileLocked;
- (void)_checkDelegateShouldTransitionForTrigger:(long long)trigger completionBlock:(id /* block */)block;
- (_Bool)_didScrollPresentLongLookViewController;
- (void)_dismissPresentedViewControllerAnimated:(_Bool)animated;
- (void)_expandedPlatterInteractionManager:(id)manager didDismissWithReason:(id)reason;
- (void)_expandedPlatterInteractionManager:(id)manager willDismissWithReason:(id)reason;
- (id)_expandedPlatterViewController;
- (void)_handlePresentedContentDismissalForClickPresentationInteractionManagerWithTrigger:(long long)trigger;
- (void)_handleTapOnView:(id)view;
- (id)_initWithNotificationRequest:(id)request revealingAdditionalContentOnPresentation:(_Bool)presentation;
- (void)_intelligenceLightAnimationIfNeeded;
- (id)_interactionManagerCreatingIfNecessary;
- (_Bool)_isLockedByAppProtection;
- (_Bool)_isPresentingCustomContentProvidingViewController;
- (void)_loadLookView;
- (id)_longLookNotificationViewController;
- (unsigned long long)_maximumNumberOfPrimaryTextLinesForProvidedStaticContent;
- (unsigned long long)_maximumNumberOfSecondaryTextLinesForProvidedStaticContent;
- (unsigned long long)_maximumNumberOfTextLinesForProvidedStaticContentWithDefaultNumber:(unsigned long long)number isPrimary:(_Bool)primary isLarge:(_Bool)large;
- (id)_newClickPresentationInteractionManager;
- (id)_notificationShortLookViewIfLoaded;
- (void)_notificationViewControllerViewDidLoad;
- (void)_presentLongLookAnimated:(_Bool)animated trigger:(long long)trigger completion:(id /* block */)completion;
- (void)_presentLongLookForScrollAnimated:(_Bool)animated completion:(id /* block */)completion;
- (void)_presentLongLookViaClickPresentationInteraction:(id /* block */)interaction;
- (void)_presentLongLookViaInteractionManager:(id /* block */)manager;
- (id)_presentedLongLookViewController;
- (id)_presentedViewController;
- (void)_requestAppProtectionUnlockWithCompletion:(id /* block */)completion;
- (id)_requiredContextIDsForDragSessionInView:(id)view;
- (void)_setActiveExpandedPlatterInteractionAnimator:(id)animator;
- (void)_setDidScrollPresentLongLookViewController:(_Bool)controller;
- (_Bool)_setNotificationRequest:(id)request;
- (_Bool)_shouldPerformHoverHighlighting;
- (_Bool)_shouldSupportExpandedPlatterInteraction;
- (_Bool)_shouldUseHapticTouch;
- (void)_updateLookView:(id)view withTitleFromProvidedStaticContent:(id)content;
- (void)_updateScreenCaptureProhibited;
- (void)_updateShortLookShadow;
- (void)_updateThumbnailForRichContentForShortLookView:(id)view withContentProvider:(id)provider;
- (void)_updateWithProvidedAuxiliaryOptionsContent;
- (void)_updateWithProvidedStaticContent;
- (id)backgroundMaterialView;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canResignFirstResponder;
- (id)clickPresentationInteractionManager;
- (void)clickPresentationInteractionManager:(id)manager declinedDismissingPresentedContentWithTrigger:(long long)trigger;
- (_Bool)clickPresentationInteractionManager:(id)manager shouldBeginInteractionWithTouchAtLocation:(struct CGPoint { double x0; double x1; })location;
- (void)clickPresentationInteractionManager:(id)manager shouldFinishInteractionThatReachedForceThreshold:(_Bool)threshold withCompletionBlock:(id /* block */)block;
- (void)clickPresentationInteractionManager:(id)manager willDismissPresentedContentWithTrigger:(long long)trigger;
- (void)clickPresentationInteractionManagerDidEndUserInteraction:(id)interaction;
- (_Bool)clickPresentationInteractionManagerShouldAllowLongPressGesture:(id)gesture;
- (void)clickPresentationInteractionManagerWillBeginUserInteraction:(id)interaction;
- (id)containerViewForClickPresentationInteractionManager:(id)manager;
- (id)containerViewForExpandedContent;
- (void)contentProvider:(id)provider performAction:(id)action animated:(_Bool)animated;
- (id)currentTraits;
- (id)customBackgroundContainerViewForExpandedPlatterPresentationController:(id)controller;
- (void)customContent:(id)content didUpdateUserNotificationActions:(id)actions;
- (_Bool)didForwardNotificationRequestToCustomContent:(id)content;
- (void)didInvalidateSizeFromNotificationShortLookView:(id)view;
- (_Bool)dismissPresentedViewControllerAnimated:(_Bool)animated;
- (void)dragInteraction:(id)interaction item:(id)item willAnimateCancelWithAnimator:(id)animator;
- (id)dragInteraction:(id)interaction itemsForBeginningSession:(id)session;
- (id)dragInteraction:(id)interaction previewForCancellingItem:(id)item withDefault:(id)_default;
- (id)dragInteraction:(id)interaction previewForLiftingItem:(id)item session:(id)session;
- (void)dragInteraction:(id)interaction session:(id)session didEndWithOperation:(unsigned long long)operation;
- (void)dragInteraction:(id)interaction session:(id)session willEndWithOperation:(unsigned long long)operation;
- (_Bool)dragInteraction:(id)interaction sessionIsRestrictedToDraggingApplication:(id)application;
- (void)dragInteraction:(id)interaction sessionWillBegin:(id)begin;
- (void)dragInteraction:(id)interaction willAnimateLiftWithAnimator:(id)animator session:(id)session;
- (void)expandAndPlayMedia;
- (void)expandedPlatter:(id)platter didDismissWithReason:(id)reason;
- (void)expandedPlatter:(id)platter willDismissWithReason:(id)reason;
- (void)expandedPlatterDidPresent:(id)present;
- (id)expandedPlatterInteractionManager:(id)manager menuWithSuggestedActions:(id)actions;
- (_Bool)expandedPlatterInteractionManager:(id)manager shouldBeginInteractionWithTouchAtLocation:(struct CGPoint { double x0; double x1; })location;
- (void)expandedPlatterInteractionManager:(id)manager shouldCommitInteraction:(id /* block */)interaction;
- (void)expandedPlatterInteractionManager:(id)manager willDismissContentWithAnimator:(id)animator;
- (void)expandedPlatterInteractionManager:(id)manager willPresentContentWithAnimator:(id)animator;
- (id)expandedPlatterInteractionManagerContainerView:(id)view;
- (id)expandedPlatterInteractionManagerContentViewController:(id)controller;
- (id)expandedPlatterInteractionManagerIdentifier:(id)identifier;
- (_Bool)expandedPlatterInteractionManagerShouldAllowInitialSwipeToDismiss:(id)dismiss;
- (_Bool)expandedPlatterInteractionManagerShouldAllowLongPressGesture:(id)gesture;
- (_Bool)expandedPlatterPresentationControllerShouldProvideBackground:(id)background;
- (long long)expandedPlatterViewController:(id)controller dateFormatStyleForNotificationRequest:(id)request;
- (void)expandedPlatterViewController:(id)controller requestsDismissalWithReason:(id)reason userInfo:(id)info;
- (void)expandedPlatterWillPresent:(id)present;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })finalDismissedFrameOfViewForPreview;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })finalPresentedFrameOfViewForPreview;
- (_Bool)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
- (void)handleWake:(_Bool)wake;
- (_Bool)hasCommittedToPresentingCustomContentProvidingViewController;
- (unsigned long long)importantAdornmentEligibleOptionsForNotificationViewController:(id)controller;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })initialPresentedFrameOfViewForPreview;
- (_Bool)isContentExtensionVisible:(id)visible;
- (_Bool)isHighlighted;
- (_Bool)isNotPresentingOrHasCommittedToDismissingCustomContentProvidingViewController;
- (_Bool)isNotificationContentViewHidden;
- (_Bool)isShortLook;
- (void)notificationViewControllerDidDismiss:(id)dismiss;
- (void)notificationViewControllerDidPresent:(id)present;
- (void)notificationViewControllerWillDismiss:(id)dismiss;
- (void)notificationViewControllerWillPresent:(id)present;
- (id)pointerInteraction:(id)interaction regionForRequest:(id)request defaultRegion:(id)region;
- (id)pointerInteraction:(id)interaction styleForRegion:(id)region;
- (void)pointerInteraction:(id)interaction willEnterRegion:(id)region animator:(id)animator;
- (void)pointerInteraction:(id)interaction willExitRegion:(id)region animator:(id)animator;
- (void)presentLongLookAnimated:(_Bool)animated trigger:(long long)trigger completion:(id /* block */)completion;
- (id)presentedExpandedPlatterViewController;
- (id)presentedViewControllerForClickPresentationInteractionManager:(id)manager;
- (_Bool)resignFirstResponder;
- (void)setContentReplacedWithSnapshot:(_Bool)snapshot;
- (void)setCustomContentHomeAffordanceGestureRecognizer:(id)recognizer;
- (void)setCustomContentHomeAffordanceVisible:(_Bool)visible;
- (void)setGlassMode:(unsigned long long)mode;
- (void)setHasShadow:(_Bool)shadow;
- (void)setHighlighted:(_Bool)highlighted;
- (void)setInteractionEnabled:(_Bool)enabled;
- (void)setMaterialGroupNameBase:(id)base;
- (void)setNotificationContentViewHidden:(_Bool)hidden;
- (void)setPlatterHighlighted:(_Bool)highlighted;
- (_Bool)shouldCommitToExpandedPlatterPresentationWithFeedback;
- (_Bool)shouldRestorePresentingShortLookOnDismiss;
- (id)transitioningDelegateForClickPresentationInteractionManager:(id)manager;
- (void)viewDidAppear:(_Bool)appear;
- (void)viewDidDisappear:(_Bool)disappear;
- (id)viewForPreview;
- (void)viewWillDisappear:(_Bool)disappear;
- (void)viewWillLayoutSubviews;
- (id)visiblePath;

@end

#endif /* NCNotificationShortLookViewController_h */