//
//   Generated by https://github.com/blacktop/ipsw (Version: v3.1.659, BuildCommit: 1a6cd4a9)
//
//    - LC_BUILD_VERSION:  Platform: iOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
//    - LC_SOURCE_VERSION: 1003.2.11.101.0
//

#ifndef NCNotificationRequest_Bulletin_h
#define NCNotificationRequest_Bulletin_h
@import Foundation;

@interface NCNotificationRequest (Bulletin) <NCNotificationListPresentable>

/* class methods */
+ (id)_notificationRequestForBulletin:(id)bulletin observer:(id)observer sectionInfo:(id)info feed:(unsigned long long)feed playLightsAndSirens:(_Bool)sirens hasPlayLightsAndSirens:(_Bool)sirens uuid:(id)uuid;
+ (id)notificationRequestForBulletin:(id)bulletin observer:(id)observer sectionInfo:(id)info feed:(unsigned long long)feed;
+ (id)notificationRequestForBulletin:(id)bulletin observer:(id)observer sectionInfo:(id)info feed:(unsigned long long)feed playLightsAndSirens:(_Bool)sirens uuid:(id)uuid;
+ (id)notificationRequestForBulletin:(id)bulletin observer:(id)observer sectionInfo:(id)info feed:(unsigned long long)feed uuid:(id)uuid;
+ (id)requesterIdentifier;

/* instance methods */
- (long long)_atxAttachmentType;
- (unsigned long long)_atxPriorityStatusFromNCNotificationRequestPriorityStatus:(unsigned long long)status;
- (unsigned long long)_atxSummaryStatusFromNCNotificationRequestSummaryStatus:(unsigned long long)status;
- (long long)_atxUrgencyFromInterruptionLevel:(unsigned long long)level;
- (id)_communicationContactIdentifiers;
- (id)attachmentImageWithDimension:(double)dimension;
- (id)atxUserNotification;
- (id)bulletin;
- (id)carPlayAttributedMessage;
- (id)carPlayMessage;
- (id)carPlayRequestIdentifier;
- (id)carPlaySubTitle;
- (id)carPlayTitle;
- (id)contactIdentifier;
- (id)defaultEnvironmentActions;
- (_Bool)hasAttachments;
- (_Bool)hasOnlySingleMinimalTextInputAction;
- (_Bool)hasOnlySingleTextInputAction;
- (_Bool)hasSameContactAsNotificationRequest:(id)request;
- (id)iconRecipe;
- (_Bool)isPriorityNotificationsEnabled;
- (_Bool)isSummarized;
- (_Bool)isSummaryEnabled;
- (id)minimalEnvironmentActions;
- (id)observer;
- (_Bool)showsTextInputOnAppearance;
- (id)subordinateIconRecipe;
- (id)summary;

@end

#endif /* NCNotificationRequest_Bulletin_h */