TWEAK_NAME = DynamicIslandTweak
DynamicIslandTweak_FILES = Tweak.x DIContentView.m DIWindow.m DIDisplayManager.m DILocalization.m
DynamicIslandTweak_CFLAGS = -fobjc-arc
DynamicIslandTweak_FRAMEWORKS = UIKit CoreGraphics QuartzCore

LOGOS_DEFAULT_GENERATOR = internal

include $(THEOS_MAKE_PATH)/tweak.mk
