name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: langshiyunyi/theos-build/.github/workflows/build.yml@v1
    with:
      scheme: both
